# SwiftLint Configuration for RollCall
# Following CLAUDE.md requirements

# Paths to include
included:
  - Sources
  - Tests
  - RollCall

# Paths to exclude
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - ${PWD}/.build
  - ${PWD}/DerivedData

# Rule configuration
opt_in_rules:
  - empty_count
  - empty_string
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_xctest_method
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - yoda_condition
  - prefer_zero_over_explicit_init
  - array_init
  - attributes
  - closure_body_length
  - conditional_returns_on_newline
  - explicit_init
  - file_header
  - implicit_return
  - number_separator
  - object_literal
  - operator_function_whitespace
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_set_access_control
  - sorted_imports
  - switch_case_on_newline
  - trailing_comma
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - single_test_class
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - unused_import
  - unused_declaration
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - function_default_parameter_at_end
  - legacy_random
  - no_extension_access_modifier
  - redundant_discardable_let
  - redundant_objc_attribute
  - static_operator
  - unavailable_function
  - explicit_top_level_acl
  - convenience_type
  - required_enum_case
  - min_length
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - duplicate_imports
  - legacy_objc_type
  - return_arrow_whitespace
  - unused_setter_value
  - trailing_whitespace
  - type_name
  - type_body_length
  - todo
  - trailing_newline
  - trailing_semicolon
  - unneeded_break_in_switch
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_whitespace
  - void_return
  - weak_delegate
  - xctfail_message

disabled_rules:
  - file_length
  - function_body_length
  - function_parameter_count
  - large_tuple
  - line_length
  - cyclomatic_complexity
  - nesting
  - identifier_name
  - multiple_closures_with_trailing_closure
  - blanket_disable_command
  - no_extension_access_modifier
  - explicit_top_level_acl
  - type_contents_order
  - conditional_returns_on_newline
  - switch_case_on_newline
  - closure_body_length
  - trailing_comma
  - number_separator
  - no_magic_numbers
  - force_unwrap_except_tests
  - prefer_nimble
  - file_types_order
  - type_body_length
  - implicitly_unwrapped_optional
  - for_where
  - single_test_class
  - non_optional_string_data_conversion
  - vertical_whitespace_between_cases
  - weak_delegate

# Custom rules
custom_rules:
  mvvm_view_model_no_ui:
    name: "ViewModel No UI Import"
    regex: "(^import (UIKit|SwiftUI|AppKit)|#if.*\\s*import (UIKit|SwiftUI|AppKit))"
    match_kinds:
      - keyword
    excluded: ".*View\\.swift|.*Tests\\.swift|.*Preview.*|.*Mock.*|.*Coordinator\\.swift"
    message: "ViewModels must not import UI frameworks (VM-1)"
    severity: error

  strong_typed_ids:
    name: "Strong Typed IDs"
    regex: "typealias\\s+(RollID|ChefID|RestaurantID)\\s*=\\s*UUID"
    message: "Use strong typing for domain models (C-5). Use struct RollID: Hashable { let value: UUID }"
    severity: error

  force_unwrap_except_tests:
    name: "Force Unwrapping"
    regex: "\\![^=&|!\\s]"
    excluded: ".*Tests\\.swift|.*Mock.*|.*TestUtilities\\.swift"
    message: "No force unwrapping except in tests (G-4)"
    severity: warning

  mainactor_on_viewmodel_class:
    name: "MainActor on ViewModel Class"
    regex: "@MainActor\\s+(final\\s+)?class\\s+\\w*ViewModel(?!Tests)"
    excluded: ".*Tests\\.swift"
    message: "ViewModels should NOT be @MainActor, only specific UI methods (VM-6)"
    severity: error

# Rule parameters
force_cast: error
force_try: error

implicitly_unwrapped_optional:
  mode: all_except_iboutlets

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2

type_name:
  min_length: 3
  max_length: 50
  allowed_symbols: ["_"]

identifier_name:
  min_length: 2
  max_length: 50
  allowed_symbols: ["_"]
  validates_start_with_lowercase: true

number_separator:
  minimum_length: 5

file_header:
  required_pattern: |
    \/\/
    \/\/ .*\.swift
    \/\/ RollCall
    \/\/
    \/\/ Created by .* on .*\.
    \/\/

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji, markdown)
reporter: "xcode"